"""harden_identity"""

import sqlalchemy as sa
from alembic import op

revision = "35b63b33b85a"
down_revision = "d3db5811f7ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_mail",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("body_ciphertext", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("account_mail", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_mail_user_id"), ["user_id"], unique=False)

    op.create_table(
        "auth_tokens",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_tokens_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "recovery_codes",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    with op.batch_alter_table("recovery_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recovery_codes_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_agent", sa.String(length=250), server_default="", nullable=False)
        )
        batch_op.add_column(sa.Column("mfa_verified_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email_verified_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("mfa_ciphertext", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("mfa_pending_ciphertext", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("mfa_pending_until", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("mfa_last_counter", sa.Integer(), server_default="-1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("mfa_last_counter")
        batch_op.drop_column("mfa_pending_until")
        batch_op.drop_column("mfa_pending_ciphertext")
        batch_op.drop_column("mfa_ciphertext")
        batch_op.drop_column("email_verified_at")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_column("mfa_verified_at")
        batch_op.drop_column("user_agent")

    with op.batch_alter_table("recovery_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recovery_codes_user_id"))

    op.drop_table("recovery_codes")
    with op.batch_alter_table("auth_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_tokens_expires_at"))

    op.drop_table("auth_tokens")
    with op.batch_alter_table("account_mail", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_mail_user_id"))

    op.drop_table("account_mail")
    # ### end Alembic commands ###
