"""Initial relational schema"""

import sqlalchemy as sa
from alembic import op

revision = "d3db5811f7ad"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_buckets",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("window", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_org_id"), ["org_id"], unique=False)

    op.create_table(
        "contacts",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("score_reason", sa.Text(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("last_contact_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("kind IN ('lead','buyer','seller','contact')"),
        sa.CheckConstraint("score >= 0 AND score <= 100"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "email"),
        sa.UniqueConstraint("org_id", "id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contacts_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_org_id"), ["org_id"], unique=False)

    op.create_table(
        "integrations",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("token_ciphertext", sa.Text(), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.String(length=100), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", "provider"),
    )
    with op.batch_alter_table("integrations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_integrations_org_id"), ["org_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "dedupe_key"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_due", ["status", "available_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_org_id"), ["org_id"], unique=False)

    op.create_table(
        "memberships",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("role IN ('owner','admin','agent','assistant','viewer')"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id"),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memberships_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memberships_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("link", sa.String(length=100), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_org_id"), ["org_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("customer_id", sa.String(length=100), nullable=True),
        sa.Column("subscription_id", sa.String(length=100), nullable=True),
        sa.Column("plan", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("trial_end", sa.DateTime(), nullable=True),
        sa.Column("period_end", sa.DateTime(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("last_event_created", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id"),
        sa.UniqueConstraint("org_id"),
        sa.UniqueConstraint("subscription_id"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subscriptions_org_id"), ["org_id"], unique=False)

    op.create_table(
        "sync_cursors",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("resource", sa.String(length=250), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", "resource"),
    )
    with op.batch_alter_table("sync_cursors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_cursors_org_id"), ["org_id"], unique=False)

    op.create_table(
        "usage",
        sa.Column("metric", sa.String(length=40), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.create_index("ix_usage_month", ["org_id", "metric", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_org_id"), ["org_id"], unique=False)

    op.create_table(
        "workflows",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("trigger", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("condition", sa.JSON(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workflows_org_id"), ["org_id"], unique=False)

    op.create_table(
        "activities",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activities_contact_id"), ["contact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_org_id"), ["org_id"], unique=False)

    op.create_table(
        "ai_actions",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("permission", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("approved_hash", sa.String(length=64), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("dedupe_key", sa.String(length=250), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "dedupe_key"),
    )
    with op.batch_alter_table("ai_actions", schema=None) as batch_op:
        batch_op.create_index("ix_action_queue", ["org_id", "status", "scheduled_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_actions_org_id"), ["org_id"], unique=False)

    op.create_table(
        "appointments",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column("location", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("calendar_id", sa.String(length=250), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("end_at > start_at"),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "external_id"),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_appointments_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_appointments_start_at"), ["start_at"], unique=False)

    op.create_table(
        "commitments",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("responsible_user", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("commitments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_commitments_org_id"), ["org_id"], unique=False)

    op.create_table(
        "communications",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("sender", sa.String(length=254), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("thread_id", sa.String(length=160), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("analyzed", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "id"),
        sa.UniqueConstraint("org_id", "owner_id", "external_id"),
    )
    with op.batch_alter_table("communications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_communications_contact_id"), ["contact_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_communications_org_id"), ["org_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_communications_thread_id"), ["thread_id"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("mime_type", sa.String(length=80), nullable=False),
        sa.Column("storage_key", sa.String(length=250), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("classification", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_org_id"), ["org_id"], unique=False)

    op.create_table(
        "facts",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("field", sa.String(length=60), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=60), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("verified_by", sa.String(length=36), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1"),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_facts_contact_id"), ["contact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_facts_org_id"), ["org_id"], unique=False)

    op.create_table(
        "oauth_states",
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("verifier", sa.String(length=100), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash"),
    )
    op.create_table(
        "preferences",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("budget_min", sa.Integer(), nullable=True),
        sa.Column("budget_max", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Float(), nullable=True),
        sa.Column("property_type", sa.String(length=40), nullable=True),
        sa.Column("timeline", sa.String(length=160), nullable=True),
        sa.Column("financing", sa.String(length=160), nullable=True),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("budget_max IS NULL OR budget_max >= 0"),
        sa.CheckConstraint("budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max"),
        sa.CheckConstraint("budget_min IS NULL OR budget_min >= 0"),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "contact_id"),
    )
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_preferences_org_id"), ["org_id"], unique=False)

    op.create_table(
        "properties",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("address", sa.String(length=250), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("bathrooms", sa.Float(), nullable=False),
        sa.Column("sqft", sa.Integer(), nullable=True),
        sa.Column("property_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("listing_reference", sa.String(length=100), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("price >= 0 AND bedrooms >= 0 AND bathrooms >= 0"),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "id"),
    )
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_properties_org_id"), ["org_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_to", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_contact_id"), ["contact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)

    op.create_table(
        "deals",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("expected_close", sa.DateTime(), nullable=True),
        sa.Column("commission_bps", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("value >= 0"),
        sa.ForeignKeyConstraint(
            ["org_id", "contact_id"],
            ["contacts.org_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "property_id"],
            ["properties.org_id", "properties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "id"),
    )
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deals_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_deals_stage"), ["stage"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("deal_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "deal_id"],
            ["deals.org_id", "deals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transactions_org_id"), ["org_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_org_id"))

    op.drop_table("transactions")
    with op.batch_alter_table("deals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deals_stage"))
        batch_op.drop_index(batch_op.f("ix_deals_org_id"))

    op.drop_table("deals")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_org_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_due_at"))
        batch_op.drop_index(batch_op.f("ix_tasks_contact_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_properties_org_id"))

    op.drop_table("properties")
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_preferences_org_id"))

    op.drop_table("preferences")
    op.drop_table("oauth_states")
    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_facts_org_id"))
        batch_op.drop_index(batch_op.f("ix_facts_contact_id"))

    op.drop_table("facts")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_org_id"))

    op.drop_table("documents")
    with op.batch_alter_table("communications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_communications_thread_id"))
        batch_op.drop_index(batch_op.f("ix_communications_org_id"))
        batch_op.drop_index(batch_op.f("ix_communications_contact_id"))

    op.drop_table("communications")
    with op.batch_alter_table("commitments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_commitments_org_id"))

    op.drop_table("commitments")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_start_at"))
        batch_op.drop_index(batch_op.f("ix_appointments_org_id"))

    op.drop_table("appointments")
    with op.batch_alter_table("ai_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_actions_org_id"))
        batch_op.drop_index("ix_action_queue")

    op.drop_table("ai_actions")
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activities_org_id"))
        batch_op.drop_index(batch_op.f("ix_activities_contact_id"))

    op.drop_table("activities")
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflows_org_id"))

    op.drop_table("workflows")
    with op.batch_alter_table("usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_org_id"))
        batch_op.drop_index("ix_usage_month")

    op.drop_table("usage")
    with op.batch_alter_table("sync_cursors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_cursors_org_id"))

    op.drop_table("sync_cursors")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_org_id"))

    op.drop_table("subscriptions")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_org_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_org_id"))

    op.drop_table("memberships")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_org_id"))
        batch_op.drop_index("ix_jobs_due")

    op.drop_table("jobs")
    with op.batch_alter_table("integrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integrations_org_id"))

    op.drop_table("integrations")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_org_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_kind"))

    op.drop_table("contacts")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_org_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    op.drop_table("webhook_events")
    op.drop_table("users")
    op.drop_table("rate_buckets")
    op.drop_table("organizations")
    # ### end Alembic commands ###
